default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: king-tide-api_development
  username: alexandrasaldana
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: king-tide-api_test
  username: alexandrasaldana
  password:
  host: localhost
  port: 5432

production:
  <<: *default
  database: king-tide-api_production
  username: alexandrasaldana
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>